CREATE DATABASE IF NOT EXISTS pwii CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE pwii;
CREATE TABLE IF NOT EXISTS usuario (
 id INT AUTO_INCREMENT PRIMARY KEY,
 nome VARCHAR(45) NOT NULL UNIQUE,
 senha VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS amigo (
 idamigo INT AUTO_INCREMENT PRIMARY KEY,
 nome VARCHAR(45) NOT NULL,
 apelido VARCHAR(45) NOT NULL,
 email VARCHAR(255) NOT NULL
);
